language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11
dist: trusty
cache:
  directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
